class recon:
    def __init__(self):
        self.ID = []
        self.SETTLEMENT = []
        self.TRANSACTIONDATE = []
        self.CARDNUMBER = []
        self.RRN = []
        self.ARN = []
        self.AUTHCODE = []
        self.MCC = []
        self.REQUESTCATEGORY = []
        self.MSGCODE = []
        self.TRXNTYPE = []
        self.AMOUNT = []
        self.CURRENCY = []
        self.MERCHANTNAME = []
        self.MERCHANTID = []
        self.ORIGCONTRACTNUMBER = []
        self.ORIGMEMBERID = []
        self.SRVC = []
        self.CPID = []
        self.PHASEDATE = []
        self.RECONCURRENCY = []
        self.RECONAMOUNT = []
